// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrookApi.Database;

#nullable disable

namespace TrookApi.Database.Migrations
{
    [DbContext(typeof(TrookDbContext))]
    [Migration("20260322161940_add_garages")]
    partial class add_garages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("TrookApi.Database.Entities.DriverJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<uint?>("CargoSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cargo_size");

                    b.Property<string>("CargoType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("cargo_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<uint>("DayCompleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day_completed");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DestinationCity")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("dest_city");

                    b.Property<string>("DestinationCompany")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("dest_company");

                    b.Property<uint>("Distance")
                        .HasColumnType("INTEGER")
                        .HasColumnName("distance");

                    b.Property<string>("DriverId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("driver_id");

                    b.Property<long>("Fuel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fuel");

                    b.Property<bool>("IsEmpty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_empty");

                    b.Property<long>("Maintenance")
                        .HasColumnType("INTEGER")
                        .HasColumnName("maintenance");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT")
                        .HasColumnName("profile_id");

                    b.Property<long>("Revenue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revenue");

                    b.Property<string>("SourceCity")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_city");

                    b.Property<string>("SourceCompany")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_company");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<long>("Wage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("wage");

                    b.HasKey("Id");

                    b.ToTable("driver_jobs");
                });

            modelBuilder.Entity("TrookApi.Database.Entities.Garage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<float>("Productivity")
                        .HasColumnType("REAL")
                        .HasColumnName("productivity");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT")
                        .HasColumnName("profile_id");

                    b.Property<uint>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("garages");
                });

            modelBuilder.Entity("TrookApi.Database.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("HeadquartersCity")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("hq_city");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT")
                        .HasColumnName("profile_id");

                    b.Property<long>("TotalDistance")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_distance");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("players");
                });

            modelBuilder.Entity("TrookApi.Database.Entities.PlayerJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("BaseDistance")
                        .HasColumnType("INTEGER")
                        .HasColumnName("base_distance");

                    b.Property<int>("BaseRevenue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("base_revenue");

                    b.Property<int>("CargoSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cargo_size");

                    b.Property<string>("CargoType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("cargo_type");

                    b.Property<float>("CargoWeight")
                        .HasColumnType("REAL")
                        .HasColumnName("cargo_weight");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DestinationCity")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("dest_city");

                    b.Property<string>("DestinationCompany")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("dest_company");

                    b.Property<int>("Distance")
                        .HasColumnType("INTEGER")
                        .HasColumnName("real_distance");

                    b.Property<int>("FinishedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("finished_at");

                    b.Property<bool>("IsQuickJob")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_quick");

                    b.Property<int>("ParkingLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parking_level");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("player_id");

                    b.Property<int>("Revenue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("real_revenue");

                    b.Property<string>("SourceCity")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_city");

                    b.Property<string>("SourceCompany")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_company");

                    b.Property<int>("StartedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("started_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int>("Xp")
                        .HasColumnType("INTEGER")
                        .HasColumnName("real_xp");

                    b.HasKey("Id");

                    b.ToTable("player_jobs");
                });

            modelBuilder.Entity("TrookApi.Database.Entities.ProcessedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<byte[]>("FileHash")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("BLOB")
                        .HasColumnName("file_hash");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_name");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_success");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("TEXT")
                        .HasColumnName("profile_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FileHash", "IsSuccess");

                    b.ToTable("processed_files");
                });

            modelBuilder.Entity("TrookApi.Database.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
